// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSkulptor.Models;

#nullable disable

namespace SkillSkulptor.Migrations
{
    [DbContext(typeof(SsDbContext))]
    [Migration("20231214162917_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillSkulptor.Models.Adress", b =>
                {
                    b.Property<int>("AdressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdressID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdressID");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("SkillSkulptor.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("Address")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Picture")
                        .HasColumnType("int");

                    b.Property<bool>("ProfileAccess")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasFilter("[Address] IS NOT NULL");

                    b.HasIndex("Picture")
                        .IsUnique()
                        .HasFilter("[Picture] IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("SkillSkulptor.Models.CV", b =>
                {
                    b.Property<int>("CVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CVID"));

                    b.Property<int>("BelongsTo")
                        .HasColumnType("int");

                    b.Property<int>("Clicks")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CVID");

                    b.HasIndex("BelongsTo")
                        .IsUnique();

                    b.ToTable("CVs");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Education", b =>
                {
                    b.Property<int>("EdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EdID"));

                    b.Property<int>("CvId")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EdID");

                    b.HasIndex("CvId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Experience", b =>
                {
                    b.Property<int>("ExId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExId"));

                    b.Property<int>("Cv")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExId");

                    b.HasIndex("Cv");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromUserID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToUserID")
                        .HasColumnType("int");

                    b.Property<bool>("ViewStatus")
                        .HasColumnType("bit");

                    b.HasKey("MessageId");

                    b.HasIndex("FromUserID");

                    b.HasIndex("ToUserID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Profilepicture", b =>
                {
                    b.Property<int>("PicrtureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PicrtureID"));

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PicrtureID");

                    b.ToTable("ProfilePictures");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Startdate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SkillSkulptor.Models.ProjectMembers", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Qualification", b =>
                {
                    b.Property<int>("QID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QID"));

                    b.Property<int>("CvId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QID");

                    b.HasIndex("CvId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("SkillSkulptor.Models.AppUser", b =>
                {
                    b.HasOne("SkillSkulptor.Models.Adress", "fkAddress")
                        .WithOne("resident")
                        .HasForeignKey("SkillSkulptor.Models.AppUser", "Address");

                    b.HasOne("SkillSkulptor.Models.Profilepicture", "fkPicture")
                        .WithOne("pictureUser")
                        .HasForeignKey("SkillSkulptor.Models.AppUser", "Picture");

                    b.Navigation("fkAddress");

                    b.Navigation("fkPicture");
                });

            modelBuilder.Entity("SkillSkulptor.Models.CV", b =>
                {
                    b.HasOne("SkillSkulptor.Models.AppUser", "fkUser")
                        .WithOne("userCV")
                        .HasForeignKey("SkillSkulptor.Models.CV", "BelongsTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fkUser");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Education", b =>
                {
                    b.HasOne("SkillSkulptor.Models.CV", "cv")
                        .WithMany("Educations")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cv");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Experience", b =>
                {
                    b.HasOne("SkillSkulptor.Models.CV", "fkCv")
                        .WithMany("Experiences")
                        .HasForeignKey("Cv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fkCv");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Message", b =>
                {
                    b.HasOne("SkillSkulptor.Models.AppUser", "fkFromUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("FromUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillSkulptor.Models.AppUser", "fkToUser")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ToUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("fkFromUser");

                    b.Navigation("fkToUser");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Project", b =>
                {
                    b.HasOne("SkillSkulptor.Models.AppUser", "CreatedByUser")
                        .WithMany("OwnProjects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("SkillSkulptor.Models.ProjectMembers", b =>
                {
                    b.HasOne("SkillSkulptor.Models.Project", "Project")
                        .WithMany("Projectmembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSkulptor.Models.AppUser", "User")
                        .WithMany("Projectmembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Qualification", b =>
                {
                    b.HasOne("SkillSkulptor.Models.CV", "fkCv")
                        .WithMany("Qualifications")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fkCv");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Adress", b =>
                {
                    b.Navigation("resident")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSkulptor.Models.AppUser", b =>
                {
                    b.Navigation("OwnProjects");

                    b.Navigation("Projectmembers");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("userCV");
                });

            modelBuilder.Entity("SkillSkulptor.Models.CV", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("SkillSkulptor.Models.Profilepicture", b =>
                {
                    b.Navigation("pictureUser")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSkulptor.Models.Project", b =>
                {
                    b.Navigation("Projectmembers");
                });
#pragma warning restore 612, 618
        }
    }
}
